### ISSUE TITLE
Bluezoo organisation

### ISSUE THREAD

**Issue by jay2u** [bluezoo/bluezoo.github.io#1]
Hi @mikehcox,

I'm Jan-Willem Korver and I am the CTO of BlueZoo, Inc.

My co-workers are giving me a real hard time over the fact that we don't have the bluezoo organisation handle on Github. The management could care less unfortunately.

Any chance you'd be willing to part with the organisation name?

Sorry I am contacting you through the issue tracker but it is my only way of reaching you.

I am a real person and not a bot :-)

Best regards,

JW

**Comment by mikehcox** [comment]
Sorry, I didn't see your "issue" until today.  If github.com has the bluezoosoftware organization free and I can rename bluezoo to bluezoosoftware and keep all the repositories, histories, issues, etc., I would be fine with that.

I found a settings page that would allow me to rename my organization to bluezoosoftware, but I don't know if github.com/bluezoosoftware is available.  Also, if it is available, renaming bluezoo to bluezoosoftware should make bluezoo immediately available, which might provide a small window to allow someone else to grab the github.com/bluezoo name.  So, if all the above conditions can be met, we can do this, but we'll have to coordinate the transition.  Let me know if you're still interested.

Mike
mhcox@bluezoosoftware.com

**Comment by mikehcox** [comment]
Connected on Google Meet to do a swap of bluezoo <-> bluezoosoftware.  Jay2u now has GitHub bluezoo organization.
